export const data = [
  {
    timeStamp: "12/14/2023 14:42",
    firm: "Hikvision",
    model: "Ds-7616ni-e2/8p",
    serial: "652437370",
    status: "Працює",
    place: "Бельведерська",
    subplace: "Кладова",
    category: "Тв",
    name: "Відеореєстратор",
  },
  {
    timeStamp: "12/14/2023 14:44",
    firm: "Невідомо",
    model: "Невідомо",
    serial: "Невідомо",
    status: "Працює",
    place: "Бельведерська",
    subplace: "Кладова",
    category: "Відеонагляд",
    name: "Poe світч",
  },
  {
    timeStamp: "12/14/2023 14:46",
    firm: "3d optical mouse",
    model: "Невідомо",
    serial: "Невідомо",
    status: "Працює",
    place: "Бельведерська",
    subplace: "Кладова",
    category: "Монітор",
    name: "Мишка до відеонагляду",
  },
  {
    timeStamp: "12/14/2023 14:46",
    firm: "3d optical mouse",
    model: "Невідомо",
    serial: "Невідомо",
    status: "В ремонті",
    place: "Бельведерська",
    subplace: "Кладова",
    category: "Відеонагляд",
    name: "Мишка до відеонагляду",
  },
  {
    timeStamp: "12/14/2023 14:46",
    firm: "3d optical mouse",
    model: "Невідомо",
    serial: "Невідомо",
    status: "Зламаний",
    place: "Бельведерська",
    subplace: "Кладова",
    category: "Відеонагляд",
    name: "Мишка до відеонагляду",
  },
  {
    timeStamp: "12/14/2023 14:46",
    firm: "3d optical mouse",
    model: "Невідомо",
    serial: "Невідомо",
    status: "В ремонті",
    place: "Шпитальна",
    subplace: "Кладова",
    category: "Відеонагляд",
    name: "Мишка до відеонагляду",
  },
  {
    timeStamp: "12/14/2023 14:46",
    firm: "3d optical mouse",
    model: "Невідомо",
    serial: "Невідомо",
    status: "Зламаний",
    place: "Шашкевича",
    subplace: "Кладова",
    category: "Відеонагляд",
    name: "Мишка до відеонагляду",
  },
];
